# This file contains the configs necessary to set up emailing
# This is required for the script to run, and 'from' requires a gmail account with insecure apps turned on

from:
  email: 'examplegmailaccount@gmail.com'
  password: 'example password'

to:
  - 'examplerecipient1@email.com'
  - 'examplerecipient2@email.com'
  - 'examplerecipient3@email.com'